### ISSUE TITLE
Refactor: Use toyaml method for source generation

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-codegen#16]
Currently I'm adding new lines to an array, and taking care to get the indenting right.

We can now use `toyaml` instead though!

**Comment by jaypeedevlin** [comment]
@clrcrl I took a pass at this today, but due to how pyyaml's dump style, the format differs substantially (despite being functionally identical).

Original Test Output:

```yaml
version: 2

models:
  - name: data__a_relation
    description: ""
    columns:
      - name: col_a
        description: ""

      - name: col_b
        description: ""

```

Test Output Using `toyaml()`:

```yaml
version: 2
models:
- name: data__a_relation
  description: ''
  columns:
  - name: col_a
    description: ''
  - name: col_b
    description: ''
```

The key differences:

- A list inside a dict is no longer indented.
- Blank lines between top-level keys and columns.
- Single quotes for empty strings instead of double quotes.

This bothers me because it departs from the fishtown style.  If dbt core replaced pyyaml with the drop-in replacement [ruamel](https://yaml.readthedocs.io/en/latest/overview.html) we could add some code there that would set the indentation (IMO the biggest issue with the change), but I haven't yet found a fix for the blank lines or single quotes.

What are your thoughts here?  Should we stick with the list of strings originally?  I like the spirit of this issue because it's a more maintainable way, but I also don't like introducing something that messes with what seems like the default dbt yaml style.
